
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  prepare:
    docker:
      - image: mbedos/mbed-os-env:latest
    working_directory: ~
    steps:
      - checkout:
          path: mbed-os-example-nfc
      - run: python3 -m pip install mbed-tools --upgrade
      - run: |
          cd mbed-os-example-nfc
          git clone https://github.com/ARMmbed/mbed-os.git
      - run:
          working_directory: mbed-os-example-nfc
          command: for i in NFC_* ; do cd $i ; ln -s $PWD/../mbed-os mbed-os ; cd .. ; done
      - persist_to_workspace:
          root: /root/project
          paths: mbed-os-example-nfc

  build_NUCLEO_F401RE:
    docker:
      - image: mbedos/mbed-os-env:stable
    working_directory: ~
    steps:
      - attach_workspace:
          at: /root/project
      - run: |
          cd mbed-os-example-nfc
          cd NFC_SmartPoster
          mbed update
          mbed compile -t GCC_ARM -m NUCLEO_F401RE || exit 1

  build_disco_l475vg:
    docker:
      - image: mbedos/mbed-os-env:stable
    working_directory: ~
    steps:
      - attach_workspace:
          at: /root/project
      - run: |
          cd mbed-os-example-nfc
          cd NFC_EEPROM
          mbed update
          mbed compile -t GCC_ARM -m DISCO_L475VG_IOT01A || exit 1

  cmake_NUCLEO_F401RE:
    docker:
      - image: mbedos/mbed-os-env:latest
    working_directory: ~
    steps:
      - attach_workspace:
          at: /root/project
      - run: |
          cd mbed-os-example-nfc
          cd NFC_SmartPoster
          mbed update
          mbed-tools compile -t GCC_ARM -m NUCLEO_F401RE || exit 1

  cmake_disco_l475vg:
    docker:
      - image: mbedos/mbed-os-env:latest
    working_directory: ~
    steps:
      - attach_workspace:
          at: /root/project
      - run: |
          cd mbed-os-example-nfc
          cd NFC_EEPROM
          mbed update
          mbed-tools compile -t GCC_ARM -m DISCO_L475VG_IOT01A || exit 1

workflows:
  version: 2
  workflow:
    jobs:
    - prepare
    - build_NUCLEO_F401RE:
        requires:
          - prepare
    - build_disco_l475vg:
        requires:
          - prepare
    - cmake_NUCLEO_F401RE:
        requires:
          - prepare
    - cmake_disco_l475vg:
        requires:
          - prepare
