name: Build example application

on:
  pull_request:
  push:

jobs: 
  build-cli-v1:
    container:
      image: ghcr.io/armmbed/mbed-os-env:master-latest

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [K64F, NUCLEO_F401RE, DISCO_L475VG_IOT01A]
        profile: [release, debug, develop]
        sub_example: [NFC_SmartPoster, NFC_EEPROM]
        

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
          
      -
        name: build-example
        run: |
          set -e
          cd ${{ matrix.sub_example }}
          mbed deploy
          mbed compile -t GCC_ARM -m ${{ matrix.target }} --profile ${{ matrix.profile }}
          

  build-cli-v2-eeprom:
    container:
      image: ghcr.io/armmbed/mbed-os-env:master-latest

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [K64F, NUCLEO_F401RE, DISCO_L475VG_IOT01A]
        profile: [release, debug, develop]
        sub_example: [NFC_EEPROM, NFC_SmartPoster]
        exclude:
          # Run NFC_SmartPoster only on NUCLEO_F401RE
          - sub_example: NFC_SmartPoster
            target: K64F
          - sub_example: NFC_SmartPoster
            target: DISCO_L475VG_IOT01A      

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
          
      -
        name: build-example-application
        run: |
          set -e
          cd ${{ matrix.sub_example }}
          mbed-tools deploy
          mbed-tools compile -t GCC_ARM -m ${{ matrix.target }} --profile ${{ matrix.profile }}
